[book]
authors = ["enhoshen"]
language = "en"
multilingual = false
src = "./"
title = "Technical-Difficulties"
[build]
create-missing = false
[output.html]
default-theme = "Navy"
[output.html.fold]
enable = true
level = 1
